import requests, pprint, json

# TMDB Auth key generated by jomathias@deloitte.com.au
# necessary to access the TMDB API data for requests.
key = '630e56aca56e58a7b972a87876d54340'

# path found from TMDB API documentation - to receive json data of movies now-playing
path = 'https://api.themoviedb.org/3/movie/now_playing?api_key=' + key + '&language=en-US&page=1&region=au'
r = requests.get(path)

#pretty print data to console (for easy reading and accessing)
data = json.dumps(json.loads(r.text), indent=4, sort_keys=True)
print(data)


#*********uncomment to create/rewrite a file now_playing.json with the data of now_playing movies**********
# f=open("now_playing.json", "w+")
# f.write(json.dumps(json.loads(r.text), indent=4, sort_keys=True))
# f.close()